# Server configuration
server.port=8081

# Database configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:4000/licypilot_db?user=postgres&password=Mn%2426052006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SQL logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE  

# Spring AI - Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3

# Aumentando o tempo de espera para a IA responder (5 minutos)
spring.ai.ollama.chat.options.timeout=600s

# Upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.servlet.multipart.max-request-size=50MB

